name: Auto Assign Project

on: [issues]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Run assignment to one project
      uses: srggrs/assign-one-project-github-action@1.1.0
      if: github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'component/expression')
      with:
        project: 'https://github.com/SunRunAway/tidb/projects/1'
