- name: Setup github/licensed
  uses: jonabc/setup-licensed@v1.0.0
  with:
    # The github/licensed version to install
    version: 
    # The target install directory for the github/licensed executable
    install-dir: # optional, default is /usr/local/bin
